# Generated by Django 3.1.3 on 2020-12-03 09:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 3, 9, 8, 16, 580882, tzinfo=utc)),
        ),
    ]
